language: go

go:
  - 1.8

sudo: required

services:
  - docker

script:
- make test
- make build

deploy:
  provider: releases
  api_key: "QQSSnXF95j9GXbgweBZSu8sXa1gL93TFmSH1DxJFEo1OiK0r8YybYmMPFyr+PdZpyH7aaRG3SHYLiQ/+0BxHXtrKKvBKbpofGfNtICEDPuFtoEs2ADts9V+aeOA6JPCVKNhLeFCComOHaeBGrL6rVZ++WdlFjaClIaUOuyINiF6LHmkESqrHgLAQxHmJXCukUSY31YltMEBMTyZHjL6Db+4W6fkP13SWumuKKMe/4wFQdec0TD8cTdXJNV7r1mfBHaW+JMhjkR358CUVY3ckyDaedreCXyR2zO8VxooN4P6M4JzEtxxmrKXiHMY8blafGSTL7+YPzzb8JhxmSztNqN7TUKmkRYqZA4nzCw9XsG7MGTkugQM2+YH3C0ltBXivj1dENfWznnJIlSAanpfjKqRDc+imPIaaVltOJuYi9kbt2fwmEDd9Kzn4D8TTs7iHtRt3xqfP9bztXlLMEGk0PBpQ0p3HjuOW7615nNwPD1QuIgu2HVLP3BtxR0lvX7eL98JXmC903aw3yfhoQIAp6tzW3P8wJ+LH104T16gqXY5iRF5/m2RlI+MvihSgs5QA2mpKUMJZxNXcnD1umXA07KhO45PaAg7AINW3V+zcbvccs6K/CGzQsnLiGQfK63aWUHNGYKE5pfWeJGee0qduE7CygACyy1lZv60lJCUsZzE="
  file: "registry-creds"
  skip_cleanup: true
  on:
    tags: true
