language: go

go:
  - 1.8

sudo: required

services:
  - docker

script:
- make test
- make build

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "registry-creds"
  skip_cleanup: true
  on:
    tags: true
